[System1]
SystemName=E-712
#CommunicationType=TCPIP
#CommunicationType=USB
#CommunicationType=RS232
CommunicationType=TCPIP
ComPortBaudrate=115200
ComPortNr=1
IPAdress=172.16.50.86
IPPort=50000
ScanRoutine1=FDR 1 2 100 3 100 L 0.2 A 1 F 15 V 20 MP1 50 MP2 50 TT 0 CM 0 MIIL 1 MAIL 99 ST 0
ScanRoutine2=FDG 2 2 3 ML 0.005 A 1 MIA 2 MAA 4 F 25 SP 50 V 200 MDC 200 SPO 0.1
ScanRoutine3=FDL 3 2 100 3 100 S 100 C 1 A 1 MT 10 MP1 50 MP2 50 CP1 1 CP2 1

[System2]
SystemName=Hexapod_Sender
#CommunicationType=TCPIP
#CommunicationType=USB
#CommunicationType=RS232
CommunicationType=TCPIP
ComPortBaudrate=115200
ComPortNr=1
IPAdress=172.16.50.11
IPPort=50000
ScanRoutine1=FDR SCAN X 0.2 Y 0.005 L -0.5 A 5 F 1 V 0.1 MP1 -3.5216 MP2 3.5617 TT 2 CM 0 MIIL 0 MAIL 80 ST 0

[System3]
SystemName=Hexapod_Receiver
#CommunicationType=TCPIP
#CommunicationType=USB
#CommunicationType=RS232
CommunicationType=TCPIP
ComPortBaudrate=115200
ComPortNr=1
IPAdress=172.16.50.27
IPPort=50000
ScanRoutine1=FDR 2 X 0.3 Y 0.01 L -0.3 A 5 F 1 V 0.1 MP1 4.462 MP2 4.0393 TT 2 CM 0 MIIL 10 MAIL 80 ST 0
ScanRoutine2=FDR FINE X 0.1 Y 0.001 L -3 A 5 F 15 V 5 MP1 4.6557 MP2 4.0134 TT 2 CM 0 MIIL 10 MAIL 80 ST 0
